# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1
  # docker: circleci/docker@2.0.3
  # heroku: circleci/heroku@1.2.6

jobs:
  unit-tests-and-linter:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv env
            . env/bin/activate
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Unit-tests
          command: pytest
      - run:
          name: Linter
          command: flake8
      - store_test_results:
          path: test-results
  

workflows:
  sample:
    jobs:
      - unit-tests-and-linter
