"""
'profiles' Django app.
It contains all the python files and folders generated by Django when starting an app.
For more information on this, see the Django documentation on the command 'manage.py startapp'.
The 'profiles' app aim to contain all the profiles related logic of the OC Lettings website.
"""
