"""
'oc_lettings_site' Django app. Main app for the Django project.
It contains all the python files and folders generated by Django when starting a project.
For more information on this, see the Django doc on the command 'django-admin startproject'.
The 'oc_lettings_site' app contain all the non-lettings specific and non-profiles specific
logic of the OC Lettings website.
"""
