"""
'lettings' Django app.
It contains all the python files and folders generated by Django when starting an app.
For more information on this, see the Django documentation on the command 'manage.py startapp'.
The 'lettings' app aim to contain all the lettings related logic of the OC Lettings website.
"""
